apiVersion: apps/v1
kind: Deployment
metadata:
  name: petite-bank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petite-bank
  template:
    metadata:
      labels:
        app: petite-bank
    spec:
      containers:
      - name: petite-bank
        image: docker.io/library/petite-bank:v2
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: petite-bank
spec:
  type: NodePort
  selector:
    app: petite-bank
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080

